plantatree/shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^order-summary/$', order_details, name="order_summary"),
]

plantatree/shopping_cart/models.py
from django.db import models

from store.models import Tree

class OrderItem(models.Model):
    product         = models.OneToOneField(Tree, on_delete=models.SET_NULL, null=True)
    is_ordered      = models.BooleanField(default=False)
    date_added      = models.DateTimeField(auto_now=True)
    date_ordered    = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name

class Order(models.Model):
    ref_code        = models.CharField(max_length=15)
    is_ordered      = models.BooleanField(default=False)
    items           = models.ManyToManyField(OrderItem)
    date_ordered    = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ref_code

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price_int() for item in self.items.all()])

plantatree/shopping_cart/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse

from store.models import Tree

from shopping_cart.extras import generate_order_id
from shopping_cart.models import OrderItem, Order

# Create your views here.
def add_to_cart(request, **kwargs):
    product = Tree.objects.filter(id=kwargs.get('item_id', "")).first()
    order_item, status = OrderItem.objects.get_or_create(product=product)
    user_order, status = Order.objects.get_or_create(is_ordered=False)
    user_order.items.add(order_item)
    if status:
        user_order.ref_code = generate_order_id()
        user_order.save()
        
    messages.info(request, "item added to cart")
    return redirect(reverse('home:home'))

def delete_from_cart(request, item_id):
    print("Here")
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))

def order_details(request, **kwargs):
    order = Order.objects.filter(is_ordered=False)
    if order.exists():
        existing_order = order[0]
    else:
        existing_order = 0
    context = {
        'order': existing_order
    }
    return render(request, 'order_summary.html', context)

plantatree/shopping_cart/templates/order_summary.html
{% extends "home/base.html" %}

{% block content %}
<section>
    <div class="row">
        <table class="table table-hover table-bordered text-center">
            <tr class="text-center">
                <th>no.</th>
                <th>Item</th>
                <th>Price</th>
            </tr>
            {% for item in order.get_cart_items %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        {{ item.product.name }}
                        <span class="pull-right">
                            <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                                <i class="fa fa-trash"></i>
                            </a>
                        </span>
                    </td>
                    <td>${{ item.product.price_int|floatformat:2 }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan=3>You have not added any items yet.</td>
                </tr>
            {% endfor %}
            <tr>
                {% if order.get_cart_total != None%}
                    <td colspan=2>
                        <strong class="pull-right">Order Total:</strong>
                    </td>

                    <td colspan=1>
                        $<strong>{{ order.get_cart_total|floatformat:2 }}</strong>
                    </td>
                {% endif %}
            </tr>
            <tr>
                <td colspan=1>
                    <a href="{% url 'home:home' %}" class="btn btn-warning pull-left">
                        {% if order.get_cart_items %}Continue Shopping{% else %}Add Items to Cart {% endif %}
                    </a>
                </td>
                <td colspan=2>
                    {% if order.get_cart_items %}
                        <a href="" class="pull-right btn btn-primary">Proceed to Checkout</a>
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
</section>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script>
        function confirm_delete() {
            return confirm("Do you want to remove this item from the cart?");
        }
    </script>
{% endblock script %}