plantatree/store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('results/', views.SearchResultsView.as_view(), name='results'),
    path('product-<int:pk>/', views.ProductView.as_view(), name='product')
]

plantatree/store/models.py
from django.db import models


# Create your models here.


class Tree(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    url = models.CharField(max_length=50)
    type = models.CharField(max_length=20)
    soil = models.CharField(max_length=1)
    sun = models.CharField(max_length=1)
    food = models.CharField(max_length=1)
    water = models.CharField(max_length=1)
    pruning = models.CharField(max_length=1)
    max_height = models.IntegerField(default=-1)
    growth_rate = models.CharField(max_length=1)
    price = models.IntegerField(default=-1)

    def price_int(self):
        return self.price / 100

    def price_str(self):
        return f'{format(self.price / 100, ",.2f")}'

    def __str__(self):
        return f'{self.name}, {self.price_str()}'

plantatree/store/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from store.models import Tree
from .searching import search_for_tree


# Create your views here.


def search(request):
    return render(request, 'store/search.html')


class SearchResultsView(ListView):
    template_name = 'store/search_results.html'
    context_object_name = 'results'
    filter_names = [
        'type',
        'soil',
        'sun',
        'food',
        'water',
        'pruning',
        'height',
        'growth',
        'price',
    ]

    def get_queryset(self):
        keywords = self.request.GET.get('search_input', '')
        filters = {
            x: self.request.GET.get(x, '')
            for x in self.filter_names
            if self.request.GET.get(x, '') is not '' and self.request.GET.get(x, '') != 'none'
        }
        return map(lambda s: ProductDisplay(s), search_for_tree(keywords, filters))


class ProductView(DetailView):
    model = Tree
    context_object_name = 'context'
    template_name = 'store/purchase.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


class ProductDisplay:
    def __init__(self, data) -> None:
        self.display = str(data)
        self.data = data

plantatree/store/templates/store/purchase.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Plant a Tree</title>
</head>
    {% extends 'home/base.html' %}
    {% block content %}
    <div class="list-group">
        <p class="list-group-item">
            {{ context.name }}
        </p>
        <p class="list-group-item">
            {{ context.description }}
        </p>
        <p class="list-group-item">
            {{ context.price_str }}
        </p>
    </div>
<form action="" method="post">
    <div class="form-group">
        <label class="control-label col-sm-2" for="age">Age</label>
        <input class="form-control col-sm-8" type="number" name="age" id="age" placeholder="Enter Preferred Age">
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="height">Height</label>
        <input class="form-control col-sm-8" type="number" name="height" id="height" placeholder="Enter Preferred Height">
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="quantity">Quantity:</label>
        <input class="form-control col-sm-8" type="number" name="quantity" id="quantity"
               placeholder="Enter Desired Quantity">
    </div>
</form>
    {% endblock content %}
</html>

plantatree/store/templates/store/search.html
{% extends "home/base.html" %}
{% block content %}
<form action="{% url 'store:results' %}" method="get">

    <div class="row">
        <div class="col-md-4 content-section form-group">
            <h2>Filters</h2>
            <label for="type">Tree Type</label>
            <select name="type" id="type" class="input-sm form-control">
                <option value="none">---</option>
                <option value="fruit">Fruit Tree</option>
                <option value="hedge">Hedge</option>
                <option value="evergreen">Evergreen</option>
                <option value="nznative">NZ Native</option>
                <option value="gumtree">Gum Tree</option>
                <option value="palmtree">Palm Tree</option>
                <option value="hardwood">Hardwood</option>
            </select>
            <br>
            <label for="soil">Soil Drainage</label>
            <select name="soil" id="soil" class="input-sm form-control">
                <option value="none">---</option>
                <option value="H">Fast</option>
                <option value="M">Medium</option>
                <option value="L">Slow</option>
            </select>
            <br>
            <label for="sun">Sun Conditions</label>
            <select name="sun" id="sun" class="input-sm form-control">
                <option value="none">---</option>
                <option value="H">Sunny</option>
                <option value="M">Medium</option>
                <option value="L">Shade</option>
            </select>
            <br>
            <label for="food">Feeding Maintenance</label>
            <select name="food" id="food" class="input-sm form-control">
                <option value="none">---</option>
                <option value="H">High</option>
                <option value="M">Medium</option>
                <option value="L">Low</option>
            </select>
            <br>
            <label for="water">Watering Maintenance</label>
            <select name="water" id="water" class="input-sm form-control">
                <option value="none">---</option>
                <option value="H">High</option>
                <option value="M">Medium</option>
                <option value="L">Low</option>
            </select>
            <br>
            <label for="pruning">Pruning Maintenance</label>
            <select name="pruning" id="pruning" class="input-sm form-control">
                <option value="none">---</option>
                <option value="H">High</option>
                <option value="M">Medium</option>
                <option value="L">Low</option>
            </select>
            <br>
            <label for="height">Max Height</label>
            <select name="height" id="height" class="input-sm form-control">
                <option value="none">---</option>
                <option value=">1">>1m</option>
                <option value="1-2">1-2m</option>
                <option value="2-3">2-3m</option>
                <option value="<3"><3m</option>
            </select>
            <br>
            <label for="growth">Growth Rate</label>
            <select name="growth" id="growth" class="input-sm form-control">
                <option value="none">---</option>
                <option value="H">High</option>
                <option value="M">Medium</option>
                <option value="L">Low</option>
            </select>
            <br>
            <label for="price">Max Price</label>
            <input type="number" id="price" name="price" class="input-sm form-control">
        </div>
        <div class="col-lg-8">
            <h1>Search Store</h1>
            <input type="text" name="search_input" id="search-bar">
            <input type="submit" value="Search">
            {% block results %}{% endblock results %}
        </div>
    </div>

</form>

{% endblock content %}

plantatree/store/templates/store/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Search Results</title>
</head>
<body>


</body>
</html>

{% extends "store/search.html" %}
{% block results %}
    {% if results %}
        <div class="list-group">
            {% for item in results %}
                <a href="{% url 'store:product' item.data.pk %}" class="list-group-item list-group-item-action">
                    {{ item.display }}
                </a>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no items that match your search</p>
    {% endif %}
{% endblock results %}