project/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('store.urls')),
    path('', include('users.urls')),
]

project/store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('results/', views.SearchResultsView.as_view(), name='results'),
]

project/tree_store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='index'),
    path('results/', views.SearchResultsView.as_view(), name='results'),
]

project/users/urls.py
from django.urls import path
from .views import register

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
]

project/home/models.py
from django.db import models

# Create your models here.

project/store/models.py
from django.db import models

# Create your models here.

class TreeItem(models.Model):
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=200)
    height = models.IntegerField(default=-1)
    age = models.IntegerField(default=-1)
    price = models.IntegerField(default=-1)
    picture_url = models.CharField(max_length=50)

    def get_dollars(self):
        return price / 100

    def __str__(self):
        return '%s, $%.2f' % (self.name, self.price / 100)

project/users/models.py
from django.db import models

# Create your models here.

project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password2']

project/home/views.py
from django.shortcuts import render

posts = [
    {
        'author': 'NoahT',
        'title': 'Learning Django',
        'content': 'first test',
        'date_posted': 'August 25, 2019'
    },
    {
        'author': 'NoahT',
        'title': 'L Django',
        'content': 'Second',
        'date_posted': 'August 252, 2019'
    }
    
]

def home(request):
    context = {
        'posts': posts
    }
    return render(request, 'home/home.html', context)

def about(request):
    return render(request, 'home/about.html', {'title': 'About'})

project/store/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import TreeItem
from django.db.models import Q
from functools import reduce

# Create your views here.
def search(request):
    return render(request, 'store/search.html')

class SearchResultsView(ListView):
    template_name = 'store/search_results.html'
    context_object_name = 'results'

    def get_queryset(self):
        return search_for_tree(self.request.GET.get('search_input', ''))

def search_for_tree(keywords):
    if keywords == '':
        return []
    queries = [Q(name__contains=kw) for kw in keywords.split()]
    query = reduce(lambda curr, new: curr | new, queries)
    return TreeItem.objects.filter(query)

project/tree_store/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import TreeItem
from django.db.models import Q
from functools import reduce

# Create your views here.
def index(request):
    return render(request, 'tree_store/index.html')

def search(request):
    return render(request, 'tree_store/search.html')

class SearchResultsView(ListView):
    template_name = 'tree_store/search_results.html'
    context_object_name = 'results'

    def get_queryset(self):
        return search_for_tree(self.request.GET.get('search_input', ''))

def search_for_tree(keywords):
    if keywords == '':
        return []
    queries = [Q(name__contains=kw) for kw in keywords.split()]
    query = reduce(lambda curr, new: curr | new, queries)
    return TreeItem.objects.filter(query)

project/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('store-home')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

project/home/templates/home/about.html
{% extends "home/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

project/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{% static 'home/main.css' %}">
    
    {% if title%}
    <title>Plant a Tree - {{ title }}</title>
    {% else %}
    <title>Plant a Tree</title>
    {% endif %}
</head>
<body>
     <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Plant a Tree</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'home:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'store:search' %}">Store</a>
              <a class="nav-item nav-link" href="{% url 'home:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="#">Login</a>
              <a class="nav-item nav-link" href="#">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
        <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                  </ul>
                </p>
          </div>
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

project/home/templates/home/home.html
{% extends "home/base.html" %}
{% block content %}
    {% for post in posts %}
        <h1>{{ post.title }}</h1>
        <p>By {{ post.author }} on {{ date_posted }}</p>
        <p>{{ post.content }}</p>
    {% endfor %}
{%endblock content%}

project/store/templates/store/search.html
{% extends "home/base.html" %}
{% block content %}

<h1>Search Store</h1>

<form action="{% url 'store:results' %}" method="get">
    <input type="text" name="search_input" id="search-bar">
    <input type="submit" value="Search">
</form>

{% endblock content %}

project/store/templates/store/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Search Results</title>
</head>
<body>


</body>
</html>

{% extends "home/base.html" %}
{% block content %}
    {% if results %}
        <h1>Search Results</h1>
        <ul>
            {% for item in results %}
                <li>
                    {{ item.name }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h1>Could not find any items that match</h1>
    {% endif %}
{%endblock content%}

project/users/templates/users/register.html
{% extends "store/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Alread Have An Account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}